### ISSUE TITLE
Unhandled Exception: Method not found

### ISSUE THREAD

**Issue by ChrisPadillaAZ** [bcleary/outlook-gmail-rules-export#8]
In an administrative Command prompt I'm running:
 OutlookRulesExport.exe username@domain.com

I get this:
Unhandled Exception: System.MissingMethodException: Method not found: 'System.Type System.Runtime.InteropServices.Marshal.GetTypeFromCLSID(System
.Guid)'.
   at OutlookRulesExport.Program.GetStore(String storeName)
   at OutlookRulesExport.Program.Main(String[] args)

Not sure if there's something I'm doing wrong.

Running:  Win7 Ent v.6.1, Office Pro 2010, Outlook v.14.0.7101.5000 (32-bit)

Thanks.
Chris.

**Comment by kenyapcomau** [comment]
I get this too. A web search for interopservices.marshal.gettypefromclsid seems to indicate that the target machine doesn't have the NET framework version wanted by the executable. Brendan, could you please recompile with a lower NET version, 4.0 I believe.

http://stackoverflow.com/questions/20440822/method-not-found-system-type-system-runtime-interopservices-marshal-gettypefro
